# Generated by Django 2.2.12 on 2020-05-22 05:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Partnerorganizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameorganization', models.TextField(verbose_name='Наименование организации')),
                ('functionorganization', models.TextField(max_length=50, verbose_name='Функции организации в проекте')),
            ],
        ),
        migrations.CreateModel(
            name='Product_of_innovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productofinnovation', models.TextField(max_length=50, verbose_name='Продукт инновационной деятельности')),
                ('suggestionsforusingtheresultsobtainedintheregionaleducationsystem', models.TextField(max_length=50, verbose_name='Предложения по использованию результатов проекта полученных  в региональной системе образования')),
            ],
        ),
        migrations.CreateModel(
            name='Prognoz_razvitia_nex_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=50, verbose_name='Задача')),
                ('nameProduct', models.TextField(max_length=50, verbose_name='Наименование продукта')),
                ('kratkoeopisanie', models.TextField(max_length=150, verbose_name='Краткое описание продукта')),
                ('sokirealizachii', models.TextField(max_length=50, verbose_name='Сроки реализации')),
            ],
        ),
        migrations.CreateModel(
            name='Project_implementation_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zadacha', models.TextField(max_length=150, verbose_name='Задача')),
                ('srokirealizatchii', models.TextField(max_length=50, verbose_name='СрокиРеализации')),
                ('otmentaovypolnenii', models.BooleanField(default=False, verbose_name='Отметка о выполнении')),
            ],
        ),
        migrations.CreateModel(
            name='Publiczna_presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(max_length=50, verbose_name='Мероприятие')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('form', models.TextField(max_length=50, verbose_name='Форма')),
                ('place', models.TextField(max_length=50, verbose_name='Место')),
                ('level', models.TextField(max_length=50, verbose_name='Уровень')),
            ],
        ),
    ]
