# Generated by Django 2.2.12 on 2020-05-25 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Publiczna_presentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField(max_length=50, verbose_name='Мероприятие')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('form', models.TextField(max_length=50, verbose_name='Форма')),
                ('place', models.TextField(max_length=50, verbose_name='Место')),
                ('level', models.TextField(max_length=50, verbose_name='Уровень')),
                ('vypolneno', models.BooleanField(default=False, verbose_name='Отметка о проверке')),
                ('publication', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Project_implementation_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zadacha', models.TextField(max_length=150, verbose_name='Задача')),
                ('srokirealizatchii', models.TextField(max_length=50, verbose_name='СрокиРеализации')),
                ('otmentaovypolnenii', models.BooleanField(default=False, verbose_name='Отметка о проверке')),
                ('publication', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prognoz_razvitia_nex_year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.TextField(max_length=50, verbose_name='Задача')),
                ('nameProduct', models.TextField(max_length=50, verbose_name='Наименование продукта')),
                ('kratkoeopisanie', models.TextField(max_length=150, verbose_name='Краткое описание продукта')),
                ('sokirealizachii', models.TextField(max_length=50, verbose_name='Сроки реализации')),
                ('vypolneno', models.BooleanField(default=False, verbose_name='Отметка о проверке')),
                ('publication', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Product_of_innovation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productofinnovation', models.TextField(max_length=50, verbose_name='Продукт инновационной деятельности')),
                ('suggestionsforusingtheresultsobtainedintheregionaleducationsystem', models.TextField(max_length=50, verbose_name='Предложения по использованию результатов проекта полученных  в региональной системе образования')),
                ('vypolneno', models.BooleanField(default=False, verbose_name='Отметка о проверке')),
                ('publication', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Partnerorganizations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameorganization', models.TextField(verbose_name='Наименование организации')),
                ('functionorganization', models.TextField(max_length=50, verbose_name='Функции организации в проекте')),
                ('vypolneno', models.BooleanField(default=False, verbose_name='Отметка о проверке')),
                ('publication', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Homework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zagolovok', models.CharField(max_length=200, verbose_name='заголовок')),
                ('Text', models.TextField(verbose_name='Текст')),
                ('Data_sozdania', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('vypolneno', models.BooleanField(default=False, verbose_name='Отметка о проверке')),
                ('publication', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('avtor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
